import fs from "fs";
import path from "path";
import { BaseConfigurator } from "./BaseConfigurator";
import { IniEditor } from "../editors/ini";
import { TomlEditor } from "../editors/toml";
import { osHandler } from "../../platform";
import { ControlsService } from "../../services/ControlsService";
import { MelonDSTranslator } from "../translators/MelonDSTranslator";
import type { EmulatorPatch, TranslateContext } from "../translators/ITranslator";

function readMelonJoystickID(filePath: string): number | null {
  if (!fs.existsSync(filePath)) return null;
  const text = fs.readFileSync(filePath, "utf-8");
  const match = text.match(/JoystickID\s*=\s*(\d+)/);
  return match ? Number(match[1]) : null;
}

export class MelonDSConfigurator extends BaseConfigurator {
  async configure(): Promise<void> {
    const svc = new ControlsService();
    const profile = svc.getDefaultProfile();

    const consoleId = "ds" as const;
    const p1 = await svc.getEffectiveConsoleBindings(consoleId, profile.id);

    const configDir = osHandler.getEmulatorConfigPath("melonds");
    const tomlPath = path.join(configDir, "melonDS.toml");
    const iniPath = path.join(configDir, "melonDS.ini");

    const hasToml = fs.existsSync(tomlPath);
    const hasIni = fs.existsSync(iniPath);

    const targetPath = hasToml ? tomlPath : hasIni ? iniPath : tomlPath;
    const targetKind: "toml" | "ini" = targetPath.endsWith(".toml") ? "toml" : "ini";

    const existingId = readMelonJoystickID(targetPath);
    if (existingId !== null && profile.melonJoystickId !== existingId) {
      profile.melonJoystickId = existingId;
      svc.saveProfile(profile);
    }

    if (!hasToml && !hasIni) {
      fs.mkdirSync(configDir, { recursive: true });

      const scaffold = [
        "# Generated by RomBox",
        "",
        "[Instance0]",
        "",
        "[Instance0.Keyboard]",
        "",
        "[Instance0.Joystick]",
        "",
      ].join("\n");

      fs.writeFileSync(targetPath, scaffold, "utf-8");
    }

    const ctx: TranslateContext = {
      platform: osHandler.getPlatform(),
      player: 1,
    };

    const joystickId = profile.melonJoystickId ?? 0;
    const patches = new MelonDSTranslator().translateFromPlayer(p1, ctx, joystickId);

    if (!patches.length) {
      console.warn("[melonds][config] no patches produced; aborting");
      return;
    }

    const updatesBySection = patchesToIniUpdates(patches);

    if (targetKind === "toml") {
      for (const [section, kv] of Object.entries(updatesBySection)) {
        if (!Object.keys(kv).length) continue;

        if (section === "") TomlEditor.updateTomlKV(targetPath, kv);
        else TomlEditor.updateTomlTableKV(targetPath, section, kv);
      }
    } else {
      IniEditor.updateIni(targetPath, updatesBySection);
    }
  }
}

function patchesToIniUpdates(patches: EmulatorPatch[]): Record<string, Record<string, string>> {
  const out: Record<string, Record<string, string>> = {};
  for (const p of patches) {
    if (p.kind !== "ini-set") continue;
    const section = (p.section ?? "").trim();
    out[section] ??= {};
    out[section][p.key] = p.value;
  }
  return out;
}