import fs from "fs";
import path from "path";
import { BaseConfigurator } from "./BaseConfigurator";
import { IniEditor } from "../ini";
import { TomlKVEditor } from "../toml";
import { osHandler } from "../../platform";
import { ControlsService } from "../../services/ControlsService";
import { MelonDSTranslator } from "../translators/MelonDSTranslator";
import type { EmulatorPatch, TranslateContext } from "../translators/ITranslator";

function readMelonJoystickID(tomlPath: string): number | null {
  if (!fs.existsSync(tomlPath)) return null;
  const text = fs.readFileSync(tomlPath, "utf-8");
  const match = text.match(/JoystickID\s*=\s*(\d+)/);
  return match ? Number(match[1]) : null;
}

export class MelonDSConfigurator extends BaseConfigurator {
  async configure(): Promise<void> {
    console.log("[melonds][config] configure() entered");
    const svc = new ControlsService();

    const profile = svc.getDefaultProfile();
    console.log(`[melonds][config] profile="${profile.name}" id=${profile.id}`);

    const ctx: TranslateContext = {
      platform: osHandler.getPlatform(),
      player: 1,
    };

    const patches = new MelonDSTranslator().translate(profile, ctx);
    console.log(`[melonds][config] translated patches=${patches.length}`);

    if (!patches.length) {
      console.warn("[melonds][config] no patches produced; aborting");
      return;
    }

    const configDir = osHandler.getEmulatorConfigPath("melonds");
    console.log(`[melonds][config] configDir=${configDir}`);

    const tomlPath = path.join(configDir, "melonDS.toml");
    const iniPath = path.join(configDir, "melonDS.ini");

    const hasToml = fs.existsSync(tomlPath);
    const hasIni = fs.existsSync(iniPath);

    const targetPath = hasToml ? tomlPath : hasIni ? iniPath : tomlPath;
    const targetKind: "toml" | "ini" = targetPath.endsWith(".toml") ? "toml" : "ini";

    const existingId = readMelonJoystickID(targetPath);
    if (existingId !== null) {
      profile.melonJoystickId = existingId;
      svc.saveProfile(profile);
    }

    if (!hasToml && !hasIni) {
      console.log("[melonds][config] no config found; creating melonDS.toml scaffold");
      fs.mkdirSync(configDir, { recursive: true });

      const scaffold = [
        "# Generated by RomBox",
        "",
        "[Instance0]",
        "",
        "[Instance0.Keyboard]",
        "",
        "[Instance0.Joystick]",
        "",
      ].join("\n");

      fs.writeFileSync(targetPath, scaffold, "utf-8");
    }

    const updatesBySection = patchesToIniUpdates(patches);

    const before = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, "utf-8") : "";

    if (targetKind === "toml") {
      for (const [section, kv] of Object.entries(updatesBySection)) {
        if (!Object.keys(kv).length) continue;

        if (section === "") {
          TomlKVEditor.updateTomlKV(targetPath, kv);
        } else {
          TomlKVEditor.updateTomlTableKV(targetPath, section, kv);
        }
      }
    } else {
      IniEditor.updateIni(targetPath, updatesBySection);
    }

    const after = fs.readFileSync(targetPath, "utf-8");
    console.log(`[melonds][config] wrote=${before !== after} path=${targetPath}`);

    console.log(`[melonds][config] target=${targetKind} sections=${Object.keys(updatesBySection).length}`);
    for (const [section, kv] of Object.entries(updatesBySection)) {
      console.log(`[melonds][config] section="${section || "(root)"}" keys=${Object.keys(kv).length}`);
    }


    console.log("[melonds][config] done");
  }
}

function patchesToIniUpdates(patches: EmulatorPatch[]): Record<string, Record<string, string>> {
  const out: Record<string, Record<string, string>> = {};
  for (const p of patches) {
    if (p.kind !== "ini-set") continue;
    const section = (p.section ?? "").trim();
    out[section] ??= {};
    out[section][p.key] = p.value;
  }
  return out;
}