import fs from "fs";
import path from "path";
import { BaseConfigurator } from "../BaseConfigurator";
import { IniEditor } from "../../utils/editors/ini";
import { TomlEditor } from "../../utils/editors/toml";
import { osHandler } from "../../platform";
import { MelonDSTranslator } from "./translator";
import type { TranslateContext } from "../translatorTypes";

function readMelonJoystickID(filePath: string): number | null {
  if (!fs.existsSync(filePath)) return null;
  const text = fs.readFileSync(filePath, "utf-8");
  const match = text.match(/JoystickID\s*=\s*(\d+)/);
  return match ? Number(match[1]) : null;
}

export class MelonDSConfigurator extends BaseConfigurator {
  async configure(): Promise<void> {
    const { controls, profile, layout, effectiveProfile } = await this.resolveControls("ds");

    const configDir = osHandler.getEmulatorConfigPath("melonds");
    const tomlPath = path.join(configDir, "melonDS.toml");
    const iniPath = path.join(configDir, "melonDS.ini");

    const hasToml = fs.existsSync(tomlPath);
    const hasIni = fs.existsSync(iniPath);

    const targetPath = hasToml ? tomlPath : hasIni ? iniPath : tomlPath;
    const targetKind: "toml" | "ini" = targetPath.endsWith(".toml") ? "toml" : "ini";

    // melonDS may have picked a different joystick since we last ran; adopt
    // whatever is on disk and persist it. effectiveProfile is a copy, so it has
    // to be updated too or the translator would write the stale id back.
    const existingId = readMelonJoystickID(targetPath);
    if (existingId !== null && profile.melonJoystickId !== existingId) {
      profile.melonJoystickId = existingId;
      effectiveProfile.melonJoystickId = existingId;
      controls.saveProfile(profile);
    }

    if (!hasToml && !hasIni) {
      fs.mkdirSync(configDir, { recursive: true });

      const scaffold = [
        "# Generated by RomBox",
        "",
        "[Instance0]",
        "",
        "[Instance0.Keyboard]",
        "",
        "[Instance0.Joystick]",
        "",
      ].join("\n");

      fs.writeFileSync(targetPath, scaffold, "utf-8");
    }

    const ctx: TranslateContext = {
      platform: osHandler.getPlatform(),
      configDir,
      player: 1,
      controllerIds: layout.controllerIds,
    };

    const patches = new MelonDSTranslator().translate(effectiveProfile, ctx);

    if (!patches.length) {
      console.warn("[melonds][config] no patches produced; aborting");
      return;
    }

    const updatesBySection = this.patchesToIniUpdates(patches);

    if (targetKind === "toml") {
      for (const [section, kv] of Object.entries(updatesBySection)) {
        if (!Object.keys(kv).length) continue;

        if (section === "") TomlEditor.updateTomlKV(targetPath, kv);
        else TomlEditor.updateTomlTableKV(targetPath, section, kv);
      }
    } else {
      IniEditor.updateIni(targetPath, updatesBySection);
    }
  }
}