import fs from "fs";
import path from "path";
import { BaseConfigurator } from "../BaseConfigurator";
import { IniEditor } from "../../utils/editors/ini";
import { TomlEditor } from "../../utils/editors/toml";
import { osHandler } from "../../platform";
import { MelonDSTranslator } from "./translator";
import type { TranslateContext, LearnedBinds } from "../translatorTypes";
import type { PlayerBindings, DigitalBinding } from "../../../shared/types/controls";
import { EngineService, getSdlProbePath, installSdlProbe } from "../../services/EngineService";
import { runSdlProbe } from "../azahar/sdlProbe";
import { Logger } from "../../utils/logger";

const log = Logger.create("MelonDSConfigurator");

function readMelonJoystickID(filePath: string): number | null {
  if (!fs.existsSync(filePath)) return null;
  const text = fs.readFileSync(filePath, "utf-8");
  const match = text.match(/JoystickID\s*=\s*(\d+)/);
  return match ? Number(match[1]) : null;
}

function looksLikeGamepadPlayer(p1: PlayerBindings): boolean {
  if (p1.move.type === "stick") return true;

  const all: (DigitalBinding | undefined)[] = [
    p1.face.primary, p1.face.secondary, p1.face.tertiary, p1.face.quaternary,
    p1.shoulders.bumperL, p1.shoulders.bumperR,
    p1.system.start, p1.system.select,
    p1.dpad.up, p1.dpad.down, p1.dpad.left, p1.dpad.right,
    p1.move.up, p1.move.down, p1.move.left, p1.move.right,
  ];

  return all.some((b) => b?.type === "gp_button" || b?.type === "gp_axis_digital");
}

async function resolveMelonConfigDir(platform: string, osConfigDir: string): Promise<string> {
  if (platform !== "win32") return osConfigDir;

  const enginePath = await EngineService.getEnginePath("melonds");
  const engineDir = enginePath ? path.dirname(enginePath) : null;
  if (!engineDir) return osConfigDir;

  const hasConfigIn = (dir: string) =>
    fs.existsSync(path.join(dir, "melonDS.toml")) || fs.existsSync(path.join(dir, "melonDS.ini"));

  if (hasConfigIn(engineDir)) return engineDir;
  if (hasConfigIn(osConfigDir)) return osConfigDir;
  return engineDir;
}

export class MelonDSConfigurator extends BaseConfigurator {
  async configure(): Promise<void> {
    const { controls, profile, layout, effectiveProfile } = await this.resolveControls("ds");

    const platform = osHandler.getPlatform();
    const configDir = await resolveMelonConfigDir(platform, osHandler.getEmulatorConfigPath("melonds"));
    const tomlPath = path.join(configDir, "melonDS.toml");
    const iniPath = path.join(configDir, "melonDS.ini");

    const hasToml = fs.existsSync(tomlPath);
    const hasIni = fs.existsSync(iniPath);

    const targetPath = hasToml ? tomlPath : hasIni ? iniPath : tomlPath;
    const targetKind: "toml" | "ini" = targetPath.endsWith(".toml") ? "toml" : "ini";

    // melonDS may have picked a different joystick since we last ran; adopt
    // whatever is on disk and persist it. effectiveProfile is a copy, so it has
    // to be updated too or the translator would write the stale id back.
    const existingId = readMelonJoystickID(targetPath);
    if (existingId !== null && profile.melonJoystickId !== existingId) {
      profile.melonJoystickId = existingId;
      effectiveProfile.melonJoystickId = existingId;
      controls.saveProfile(profile);
    }

    if (!hasToml && !hasIni) {
      fs.mkdirSync(configDir, { recursive: true });

      const scaffold = [
        "# Generated by RomBox",
        "",
        "[Instance0]",
        "",
        "[Instance0.Keyboard]",
        "",
        "[Instance0.Joystick]",
        "",
      ].join("\n");

      fs.writeFileSync(targetPath, scaffold, "utf-8");
    }

    let learnedBinds: LearnedBinds | undefined;
    if (looksLikeGamepadPlayer(effectiveProfile.player1)) {
      try {
        let probeHelperPath = getSdlProbePath();
        if (!fs.existsSync(probeHelperPath)) {
          const installed = installSdlProbe();
          if (installed.dest) probeHelperPath = installed.dest;
        }
        if (fs.existsSync(probeHelperPath)) {
          const probed = runSdlProbe({ helperPath: probeHelperPath, timeoutMs: 1500 });
          if (probed.learned?.binds) learnedBinds = probed.learned.binds as LearnedBinds;
        } else {
          log.warn("SDL probe helper missing after install attempt", { probeHelperPath });
        }
      } catch (err) {
        log.warn("SDL probe failed; falling back to static joy-code table", err);
      }
    }

    const ctx: TranslateContext = {
      platform: osHandler.getPlatform(),
      configDir,
      player: 1,
      controllerIds: layout.controllerIds,
      learnedBinds,
    };

    const patches = new MelonDSTranslator().translate(effectiveProfile, ctx);

    if (!patches.length) {
      console.warn("[melonds][config] no patches produced; aborting");
      return;
    }

    const updatesBySection = this.patchesToIniUpdates(patches);

    if (targetKind === "toml") {
      for (const [section, kv] of Object.entries(updatesBySection)) {
        if (!Object.keys(kv).length) continue;

        if (section === "") TomlEditor.updateTomlKV(targetPath, kv);
        else TomlEditor.updateTomlTableKV(targetPath, section, kv);
      }
    } else {
      IniEditor.updateIni(targetPath, updatesBySection);
    }
  }
}