import { app, BrowserWindow, ipcMain } from 'electron';
import { initDB } from './data/db';
import registerGameHandlers from './ipc/gameHandlers';
import registerEngineHandlers from './ipc/engineHandlers';
import { ScannerService } from './services/ScannerService';
import { LibraryService } from './services/LibraryService';
import { EngineService } from './services/EngineService';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

app.on('ready', () => {
  initDB(); // Initialize DB

  // Register IPC (API)
  registerGameHandlers();
  registerEngineHandlers();
  
  createWindow();
});

// Refactored File Drop Handler
ipcMain.handle('process-file-drop', async (_, filePath) => {
  try {
    // scan
    const result = await ScannerService.scanFile(filePath);

    if (result.type === 'game') {
      // import
      const gameData = await ScannerService.importGame(result);
      // save to db
      const game = await LibraryService.createGame(gameData);
      return { success: true, type: 'game', game };
    } 
    else if (result.type === 'bios') {
      // install bios
      await EngineService.installBios(result.consoleId, result.filePath);
      return { success: true, type: 'bios' };
    }
    return { success: false, message: "Unknown file" };
  } catch (err: any) {
    console.error("Drop failed:", err);
    return { success: false, message: err.message };
  }
});