import { app, BrowserWindow, ipcMain } from 'electron';
import { initDB } from './db';
import type { Game } from '../shared/types';
import { gameController } from './controllers/gameController';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

app.on('ready', () => {
  initDB();
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

ipcMain.handle('create-game', (event, fileInfo) => {
  try {
    console.log('Received file for creation:', fileInfo);
    const newGame = gameController.createGame(fileInfo);
    return { success: true, game: newGame };
  } catch (err) {
    console.error('Failed to create game:', err);
    return { success: false, message: err.message };
  }
});

ipcMain.handle('get-games', () => {
  try {
    const games = gameController.getGames();
    return { success: true, games };
  } catch (err) {
    console.error('Failed to fetch games:', err);
    return { success: false, error: err.message };
  }
});